# Generated by Django 4.2.7 on 2026-01-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gradingscale",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="gradingscale",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="gradingscale",
            name="min_score",
        ),
        migrations.AddField(
            model_name="classsection",
            name="grade_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="gradingscale",
            name="ranges",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="gradingscale",
            name="scale_type",
            field=models.CharField(default="letter", max_length=50),
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="GradingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "school")},
            },
        ),
    ]
