# Generated by Django 4.2.7 on 2026-01-20 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_remove_gradingscale_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsection",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
