# Generated by Django 5.2.7 on 2026-01-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_alter_attendance_date_alter_attendance_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="is_override",
            field=models.BooleanField(default=False),
        ),
    ]
