"""
Report Template Customization utilities
"""

from django.db import models
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
import json
import uuid

# Import models from the main models module
from .models import ReportTemplate, TemplateSection, TemplateField, ReportTemplateUsage, School, User


def create_default_template(school, user=None):
    """Create a default report template for a school"""
    
    default_template = ReportTemplate.objects.create(
        name="Default Template",
        school=school,
        template_type='custom',
        is_default=True,
        created_by=user,
        # Default styling
        header_background_color='#ffffff',
        header_text_color='#000000',
        font_family='Arial, sans-serif',
        font_size=12,
        heading_font_size=16,
        primary_color='#007bff',
        secondary_color='#6c757d',
        border_style='solid',
        border_color='#dee2e6',
        # Default content
        report_title='Report Card',
        grading_period_label='Grading Period',
        teacher_label='Class Teacher',
        principal_label='Principal',
        footer_text=f'Generated by {school.name} Report System',
        show_school_stamp=True,
        show_contact_info=True,
    )
    
    # Create default sections
    sections = [
        {'section_type': 'header', 'title': 'School Header', 'order': 1},
        {'section_type': 'student_info', 'title': 'Student Information', 'order': 2},
        {'section_type': 'academic_performance', 'title': 'Academic Performance', 'order': 3},
        {'section_type': 'attendance', 'title': 'Attendance Summary', 'order': 4},
        {'section_type': 'teacher_comments', 'title': 'Teacher Comments', 'order': 5},
        {'section_type': 'principal_comments', 'title': 'Principal Comments', 'order': 6},
        {'section_type': 'footer', 'title': 'Footer', 'order': 7},
    ]
    
    for section_data in sections:
        TemplateSection.objects.create(
            template=default_template,
            **section_data
        )
    
    return default_template


def get_school_template(school):
    """Get the default template for a school, or create one if none exists"""
    template = ReportTemplate.objects.filter(school=school, is_default=True, is_active=True).first()
    if not template:
        template = create_default_template(school)
    return template


def duplicate_template(template, new_name=None):
    """Duplicate a template with a new name"""
    if not new_name:
        new_name = f"{template.name} (Copy)"
    
    new_template = ReportTemplate.objects.create(
        name=new_name,
        school=template.school,
        template_type=template.template_type,
        is_default=False,
        header_logo=template.header_logo,
        header_background_color=template.header_background_color,
        header_text_color=template.header_text_color,
        font_family=template.font_family,
        font_size=template.font_size,
        heading_font_size=template.heading_font_size,
        primary_color=template.primary_color,
        secondary_color=template.secondary_color,
        border_style=template.border_style,
        border_color=template.border_color,
        report_title=template.report_title,
        grading_period_label=template.grading_period_label,
        teacher_label=template.teacher_label,
        principal_label=template.principal_label,
        footer_text=template.footer_text,
        show_school_stamp=template.show_school_stamp,
        show_contact_info=template.show_contact_info,
        custom_fields=template.custom_fields,
        created_by=template.created_by,
    )
    
    # Copy sections
    for section in template.sections.all():
        TemplateSection.objects.create(
            template=new_template,
            section_type=section.section_type,
            title=section.title,
            order=section.order,
            is_visible=section.is_visible,
            css_class=section.css_class,
            show_border=section.show_border,
            background_color=section.background_color,
            text_color=section.text_color,
            content_template=section.content_template,
        )
    
    # Copy custom fields
    for field in template.custom_fields.all():
        TemplateField.objects.create(
            template=new_template,
            name=field.name,
            field_key=field.field_key,
            field_type=field.field_type,
            order=field.order,
            is_required=field.is_required,
            options=field.options,
            default_value=field.default_value,
        )
    
    return new_template