# Generated by Django 5.2.7 on 2026-01-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsection",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="class_sections", to="apps.subject"
            ),
        ),
    ]
