# Generated by Django 5.2.7 on 2026-01-29 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_classsection_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for identification", max_length=200
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary School"),
                            ("secondary", "Secondary School"),
                            ("university", "University"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "header_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="report_templates/logos/"
                    ),
                ),
                (
                    "header_background_color",
                    models.CharField(
                        default="#ffffff", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "header_text_color",
                    models.CharField(
                        default="#000000", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "font_family",
                    models.CharField(default="Arial, sans-serif", max_length=100),
                ),
                (
                    "font_size",
                    models.PositiveIntegerField(
                        default=12, help_text="Base font size in px"
                    ),
                ),
                (
                    "heading_font_size",
                    models.PositiveIntegerField(
                        default=16, help_text="Heading font size in px"
                    ),
                ),
                ("include_student_photo", models.BooleanField(default=True)),
                ("include_teacher_comments", models.BooleanField(default=True)),
                ("include_principal_signature", models.BooleanField(default=True)),
                ("include_grading_scale", models.BooleanField(default=True)),
                ("include_attendance_summary", models.BooleanField(default=True)),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional custom fields"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff", help_text="Primary brand color", max_length=7
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Secondary brand color",
                        max_length=7,
                    ),
                ),
                (
                    "border_style",
                    models.CharField(
                        choices=[
                            ("solid", "Solid"),
                            ("dashed", "Dashed"),
                            ("dotted", "Dotted"),
                            ("none", "None"),
                        ],
                        default="solid",
                        max_length=20,
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#dee2e6", help_text="Border color", max_length=7
                    ),
                ),
                (
                    "report_title",
                    models.CharField(default="Report Card", max_length=200),
                ),
                (
                    "grading_period_label",
                    models.CharField(default="Grading Period", max_length=100),
                ),
                (
                    "teacher_label",
                    models.CharField(default="Class Teacher", max_length=100),
                ),
                (
                    "principal_label",
                    models.CharField(default="Principal", max_length=100),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, help_text="Custom footer text"),
                ),
                ("show_school_stamp", models.BooleanField(default=True)),
                ("show_contact_info", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Set as default template for school"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="apps.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="School logo for reports and branding",
                        null=True,
                        upload_to="school_logos/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon for the school's custom domain",
                        null=True,
                        upload_to="school_favicons/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#667eea",
                        help_text="Primary brand color (hex format, e.g., #667eea)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#764ba2",
                        help_text="Secondary brand color (hex format)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#28a745",
                        help_text="Accent color for buttons and highlights",
                        max_length=7,
                    ),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True,
                        help_text="Custom domain for the school (e.g., schoolname.reportcardapp.com)",
                        max_length=200,
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="School address")),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="School contact phone", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="School contact email", max_length=254
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="School website URL"),
                ),
                (
                    "report_header",
                    models.CharField(
                        blank=True,
                        help_text="Custom header text for report cards",
                        max_length=200,
                    ),
                ),
                (
                    "report_footer",
                    models.CharField(
                        blank=True,
                        help_text="Custom footer text for report cards",
                        max_length=300,
                    ),
                ),
                (
                    "report_signature",
                    models.CharField(
                        blank=True,
                        help_text="Principal/Head signature name",
                        max_length=100,
                    ),
                ),
                (
                    "enable_analytics",
                    models.BooleanField(
                        default=True,
                        help_text="Enable analytics dashboard for this school",
                    ),
                ),
                (
                    "enable_support_portal",
                    models.BooleanField(
                        default=True, help_text="Enable support ticket system"
                    ),
                ),
                (
                    "enable_custom_templates",
                    models.BooleanField(
                        default=True, help_text="Enable custom report templates"
                    ),
                ),
                (
                    "default_report_template",
                    models.CharField(
                        choices=[
                            ("default", "Default Template"),
                            ("modern", "Modern Template"),
                            ("classic", "Classic Template"),
                            ("minimal", "Minimal Template"),
                        ],
                        default="default",
                        help_text="Default template for report card generation",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="apps.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Profile",
                "verbose_name_plural": "School Profiles",
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.school"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.reporttemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "school")},
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Technical, Account, Feature Request",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["admin", "super_admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.school"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="apps_suppor_status_4b3536_idx",
                    ),
                    models.Index(
                        fields=["school", "status"],
                        name="apps_suppor_school__87ef99_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Field display name", max_length=100),
                ),
                (
                    "field_key",
                    models.CharField(help_text="Internal field key", max_length=50),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Yes/No"),
                            ("select", "Dropdown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, help_text="Options for select fields"
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, help_text="Default value", max_length=200
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_fields",
                        to="apps.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "field_key")},
            },
        ),
        migrations.CreateModel(
            name="TemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("header", "Header"),
                            ("student_info", "Student Information"),
                            ("academic_performance", "Academic Performance"),
                            ("attendance", "Attendance"),
                            ("teacher_comments", "Teacher Comments"),
                            ("principal_comments", "Principal Comments"),
                            ("footer", "Footer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "css_class",
                    models.CharField(
                        blank=True, help_text="Custom CSS class", max_length=100
                    ),
                ),
                ("show_border", models.BooleanField(default=True)),
                (
                    "background_color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True, help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "content_template",
                    models.TextField(
                        blank=True, help_text="HTML template for this section"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="apps.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "section_type")},
            },
        ),
    ]
