# Generated by Django 5.2.7 on 2026-01-30 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_create_reportcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__in": ["admin", "teacher"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_report_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "grading_period"],
                name="apps_grade_student_a9c54d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["subject", "grading_period"],
                name="apps_grade_subject_d4b392_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["school", "grading_period"],
                name="apps_grade_school__02f9d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "school"], name="apps_grade_student_45516b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(
                fields=["student", "grading_period"],
                name="apps_report_student_b18473_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(
                fields=["status", "is_published"], name="apps_report_status_a4a791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportcard",
            index=models.Index(
                fields=["school", "status"], name="apps_report_school__682d12_idx"
            ),
        ),
    ]
